const journeyData = [
    {
        id: "meknes",
        city: "Meknès",
        city_de: "Meknès",
        country: "Maroc",
        country_de: "Marokko",
        transport: "train",
        theme: "morocco-meknes",
        text: `Il y avait aussi une tradition : à l’arrivée dans notre village natal, il fallait rendre visite aux morts. Mon père et ma grand-mère sont enterrés à côté, une drôle de coïncidence. Mon père n’était pas du tout marocain. Il était né en Égypte et avait immigré en Suisse pour devenir ingénieur informaticien, alors que le métier en était encore à ses débuts. Il est décédé d’un cancer du cerveau quand j’avais six ans.\n\nJ’aime bien le Maroc. C’est un endroit très vrai, où le superficiel n’a pas sa place. Lorsque je rendis visite à une amie de la famille, Soukaina Boubia, professeur d’histoire-géographie à la Haute École de tourisme de Rabat-Salé, elle m’offrit un livre sur l’histoire du Maroc. C’est un très beau cadeau : offrir le savoir.`,
        text_de: `Es gab auch eine Tradition: Bei der Ankunft in unserem Heimatdorf mussten wir die Toten besuchen. Mein Vater und mein Großvater sind nebeneinander begraben, ein seltsamer Zufall. Mein Vater war überhaupt kein Marokkaner. Er wurde in Ägypten geboren und war in die Schweiz eingewandert, um Informatikingenieur zu werden, als der Beruf noch in den Kinderschuhen steckte. Er starb an Hirnkrebs, als ich sechs Jahre alt war.\n\nIch mag Marokko sehr. Es ist ein sehr authentischer Ort, an dem Oberflächlichkeit keinen Platz hat. Als ich eine Freundin der Familie besuchte, Soukaina Boubia, Professorin für Geschichte und Geographie an der Tourismushochschule in Rabat-Salé, schenkte sie mir ein Buch über die Geschichte Marokkos. Es ist ein sehr schönes Geschenk: Wissen zu verschenken.`,
        images: [
            "images/meknes/000118380040.jpg",
            "images/meknes/IMG_0043.JPG",
            "images/meknes/IMG_0047.JPG",
            "images/meknes/IMG_0061.JPG",
            "images/meknes/IMG_0083.JPG",
            "images/meknes/IMG_0090.JPG",
            "images/meknes/IMG_0096.JPG",
            "images/meknes/IMG_0101.JPG",
            "images/meknes/IMG_0113.JPG",
            "images/meknes/IMG_0114.JPG",
            "images/meknes/IMG_0122.JPG",
            "images/meknes/IMG_0135.JPG",
            "images/meknes/IMG_0136.JPG",
            "images/meknes/IMG_0137.JPG",
            "images/meknes/IMG_0138.JPG",
            "images/meknes/IMG_0141.JPG",
            "images/meknes/IMG_0149.JPG"
        ]
    },
    {
        id: "rabat",
        city: "Rabat",
        city_de: "Rabat",
        country: "Maroc",
        country_de: "Marokko",
        transport: "avion",
        theme: "morocco-rabat",
        text: `Je rejoignis ma famille à l’avenue Hassan, près du mausolée de Mohamed V. Nous nous rendîmes directement à la gare ferroviaire et prîmes le train Al Atlas, qui relie les grandes villes marocaines.\n\nDans mon compartiment, à part ma sœur et ma mère, il y avait un homme dans un coin qui lisait son journal pendant tout le trajet. À côté, toute une famille était également présente : la grand-mère, la mère, la fille et la petite fille.\n\nMa mère me raconta une habitude de ses années étudiantes, lorsqu’elle faisait la navette entre Rabat et Meknès. À l’arrivée à une gare, ses camarades masculins ouvraient toujours les portes alors que le train était encore en approche, prétendant que c’était pour s’aérer.`,
        text_de: `Ich traf meine Familie auf der Avenue Hassan, in der Nähe des Mausoleums von Mohamed V. Wir fuhren direkt zum Bahnhof und nahmen den Al Atlas-Zug, der die großen marokkanischen Städte verbindet.\n\nIn meinem Abteil saßen außer meiner Schwester und meiner Mutter noch ein Mann in einer Ecke, der während der gesamten Fahrt seine Zeitung las. Daneben war auch eine ganze Familie anwesend: die Großmutter, die Mutter, die Tochter und die Enkelin.\n\nMeine Mutter erzählte mir von einer Gewohnheit aus ihrer Studienzeit, als sie zwischen Rabat und Meknès pendelte. Bei der Einfahrt in einen Bahnhof öffneten ihre männlichen Kommilitonen immer die Türen, während der Zug noch in Bewegung war, und behaupteten, das sei zum Lüften.`,
        images: [
            "images/rabat/000118380036.jpg",
            "images/rabat/000118380037.jpg",
            "images/rabat/000118380038.jpg",
            "images/rabat/000118380039.jpg",
            "images/rabat/IMG_0164.JPG",
            "images/rabat/IMG_0169.JPG",
            "images/rabat/IMG_0176.JPG",
            "images/rabat/IMG_0189.JPG",
            "images/rabat/IMG_0190.JPG",
            "images/rabat/IMG_0193.JPG",
            "images/rabat/IMG_0246.JPG",
            "images/rabat/IMG_0255.JPG",
            "images/rabat/IMG_0301.JPG",
            "images/rabat/IMG_0303.JPG",
            "images/rabat/IMG_0310.JPG",
            "images/rabat/IMG_0317.JPG",
            "images/rabat/IMG_0318.JPG"
        ]
    },
    {
        id: "paris",
        city: "Paris",
        city_de: "Paris",
        country: "France",
        country_de: "Frankreich",
        transport: "avion",
        theme: "paris",
        text: `Paris Paris, ville lumière, ville des arts, mais surtout ville de misère. On entend souvent dire que les inégalités sont aujourd’hui plus fortes que du temps de la Révolution française.\n\nLe lendemain, je me levai pour continuer ma visite. Objectif : banlieue. Je me dirigeai vers le quartier qui me correspondrait : Barbès-Rochechouart, un quartier à forte population maghrébine.\n\nL’après-midi, je me rends au cimetière du Père-Lachaise. Je suis allé voir quelques tombes précises pour, en quelque sorte, recevoir leur bénédiction : Guillaume Apollinaire, Frédéric Chopin, Jean-Baptiste Poquelin, etc.`,
        text_de: `Paris Paris, Stadt des Lichts, Stadt der Künste, aber vor allem Stadt des Elends. Man hört oft, dass die Ungleichheiten heute größer sind als zur Zeit der Französischen Revolution.\n\nAm nächsten Tag stand ich auf, um meine Besichtigung fortzusetzen. Ziel: Vorstadt. Ich machte mich auf den Weg in das Viertel, das zu mir passen würde: Barbès-Rochechouart, ein Viertel mit einem hohen maghrebinischen Bevölkerungsanteil.\n\nAm Nachmittag gehe ich zum Friedhof Père-Lachaise. Ich besuchte einige bestimmte Gräber, um sozusagen ihren Segen zu empfangen: Guillaume Apollinaire, Frédéric Chopin, Jean-Baptiste Poquelin usw.`,
        images: [
            "images/paris/IMG_0377.JPG",
            "images/paris/IMG_0380.JPG",
            "images/paris/IMG_0410.JPG",
            "images/paris/IMG_0420.JPG",
            "images/paris/IMG_0422.JPG",
            "images/paris/IMG_0430.JPG",
            "images/paris/IMG_0456.JPG",
            "images/paris/IMG_0458.JPG",
            "images/paris/IMG_0516.JPG",
            "images/paris/IMG_0523.JPG",
            "images/paris/IMG_0524.JPG",
            "images/paris/IMG_0534.JPG",
            "images/paris/IMG_0539.JPG",
            "images/paris/IMG_0541.JPG",
            "images/paris/IMG_0543.JPG",
            "images/paris/IMG_0557.JPG",
            "images/paris/IMG_0566.JPG",
            "images/paris/IMG_0574.JPG",
            "images/paris/IMG_0575.JPG",
            "images/paris/IMG_0584.JPG",
            "images/paris/IMG_0613.JPG",
            "images/paris/IMG_0651.JPG"
        ]
    },
    {
        id: "stockholm",
        city: "Stockholm",
        city_de: "Stockholm",
        country: "Suède",
        country_de: "Schweden",
        transport: "avion",
        theme: "sweden",
        text: `J’arrive à l’aéroport de Stockholm-Arlanda à 00h20. C’est la première fois que je ne comprends rien. Où sont les belles blondes pour me guider vers mon hôtel ?\n\nJ’aime bien Stockholm : les cinnamon rolls, Ikea, et leur lait d’avoine. Je pense que je pourrais y vivre quelque temps. Mais il me reste quand même ce sentiment qu’au fond, je ne serai jamais vraiment accepté.`,
        text_de: `Ich komme um 00:20 Uhr am Flughafen Stockholm-Arlanda an. Es ist das erste Mal, dass ich gar nichts verstehe. Wo sind die schönen Blondinen, die mich zu meinem Hotel führen?\n\nIch mag Stockholm sehr: die Zimtschnecken, Ikea und ihre Hafermilch. Ich denke, ich könnte eine Zeit lang dort leben. Aber es bleibt mir trotzdem das Gefühl, dass ich im Grunde nie wirklich akzeptiert werde.`,
        images: [
            { src: "images/stockholm/IMG_0660.JPG", name: "BILLY Bibliothèque", name_de: "BILLY Bücherregal", price: 599 },
            { src: "images/stockholm/IMG_0663.JPG", name: "POÄNG Fauteuil", name_de: "POÄNG Sessel", price: 899 },
            { src: "images/stockholm/IMG_0687.JPG", name: "KALLAX Étagère", name_de: "KALLAX Regal", price: 499 },
            { src: "images/stockholm/IMG_0689.JPG", name: "MALM Lit", name_de: "MALM Bett", price: 1995 },
            { src: "images/stockholm/IMG_0697.JPG", name: "STOCKHOLM Miroir", name_de: "STOCKHOLM Spiegel", price: 799 },
            { src: "images/stockholm/IMG_0730.JPG", name: "HEMNES Commode", name_de: "HEMNES Kommode", price: 1495 },
            { src: "images/stockholm/IMG_0742.JPG", name: "LACK Table", name_de: "LACK Tisch", price: 99 },
            { src: "images/stockholm/IMG_0743.JPG", name: "FÄRGKLAR Assiette", name_de: "FÄRGKLAR Teller", price: 49 },
            "images/stockholm/IMG_0744.JPG",
            "images/stockholm/IMG_0761.JPG",
            "images/stockholm/IMG_0775.JPG",
            "images/stockholm/IMG_0777.JPG",
            "images/stockholm/IMG_0781.JPG",
            "images/stockholm/IMG_0786.JPG",
            "images/stockholm/IMG_0794.JPG",
            "images/stockholm/IMG_0797.JPG",
            "images/stockholm/IMG_0828.JPG",
            "images/stockholm/IMG_0863.JPG",
            "images/stockholm/IMG_0867.JPG",
            "images/stockholm/IMG_0868.JPG",
            "images/stockholm/IMG_0905.JPG"
        ]
    },
    {
        id: "helsinki",
        city: "Helsinki",
        city_de: "Helsinki",
        country: "Finlande",
        country_de: "Finnland",
        transport: "bateau",
        theme: "finland",
        text: `C’est seulement après avoir découvert les Moomins que j’ai commencé à apprécier Helsinki. La nuit tombe tellement vite. Elle s’écrase.\n\nLe départ de ce pays fut fabuleux. Sur le pont d’un ferry, je voyais défiler d’abord Helsinki, puis ses îles, et je me retrouvais sur la mer du Nord. Une immensité de bleu à perte de vue.`,
        text_de: `Erst nachdem ich die Mumins entdeckt hatte, begann ich Helsinki zu schätzen. Die Nacht bricht so schnell herein. Sie erdrückt einen.\n\nDer Abschied von diesem Land war fabelhaft. Auf dem Deck einer Fähre sah ich erst Helsinki vorbeiziehen, dann seine Inseln, und ich fand mich auf der Nordsee wieder. Eine Unermesslichkeit von Blau, so weit das Auge reicht.`,
        images: [
            "images/helsinki/000118380034.jpg",
            "images/helsinki/IMG_1005.JPG",
            "images/helsinki/IMG_1007.JPG",
            "images/helsinki/IMG_1013.JPG",
            "images/helsinki/IMG_1014.JPG",
            "images/helsinki/IMG_1016.JPG",
            "images/helsinki/IMG_1018.JPG",
            "images/helsinki/IMG_1043.JPG",
            "images/helsinki/IMG_1056.JPG",
            "images/helsinki/IMG_1074.JPG",
            "images/helsinki/IMG_1077.JPG",
            "images/helsinki/IMG_1078.JPG",
            "images/helsinki/IMG_1080.JPG",
            "images/helsinki/IMG_1085.JPG",
            "images/helsinki/IMG_1117.JPG",
            "images/helsinki/IMG_1131.JPG",
            "images/helsinki/IMG_1192.JPG",
            "images/helsinki/IMG_1194.JPG",
            "images/helsinki/IMG_1234.JPG",
            "images/helsinki/IMG_1277.JPG",
            "images/helsinki/IMG_1306.JPG",
            "images/helsinki/IMG_1313.JPG",
            "images/helsinki/IMG_1322.JPG",
            "images/helsinki/IMG_1330.JPG",
            "images/helsinki/IMG_1359.JPG"
        ]
    },
    {
        id: "tallinn",
        city: "Tallinn",
        city_de: "Tallinn",
        country: "Estonie",
        country_de: "Estland",
        transport: "bus",
        theme: "estonia",
        text: `Ce qui m’a surpris à Tallinn, c’est la manière dont ce pays est passé d’un pays communiste à un pays européen comme les autres. Certes, il restait des vestiges, mais la comparaison avec la Suisse était tentante.\n\nJe visitai le musée national des arts estoniens. L’approche critique et sociale a été déclenchée par les profondes inégalités ressenties dans la société des années 1990.`,
        text_de: `Was mich in Tallinn überrascht hat, ist die Art und Weise, wie dieses Land von einem kommunistischen zu einem europäischen Land wie jedes andere geworden ist. Sicherlich gab es noch Überbleibsel, aber der Vergleich mit der Schweiz war verlockend.\n\nIch besuchte das Estnische Kunstmuseum. Der kritische und soziale Ansatz wurde durch die tiefen Ungleichheiten ausgelöst, die in der Gesellschaft der 1990er Jahre zu spüren waren.`,
        images: [
            "images/tallinn/000118380030.jpg",
            "images/tallinn/000118380031.jpg",
            "images/tallinn/000118380032.jpg",
            "images/tallinn/000118380033.jpg",
            "images/tallinn/IMG_1332.JPG",
            "images/tallinn/IMG_1387.JPG",
            "images/tallinn/IMG_1395.JPG",
            "images/tallinn/IMG_1399.JPG",
            "images/tallinn/IMG_1407.JPG",
            "images/tallinn/IMG_1427.JPG",
            "images/tallinn/IMG_1429.JPG",
            "images/tallinn/IMG_1434.JPG",
            "images/tallinn/IMG_1438.JPG",
            "images/tallinn/IMG_1447.JPG",
            "images/tallinn/IMG_1506.JPG",
            "images/tallinn/IMG_1510.JPG",
            "images/tallinn/IMG_1514.JPG",
            "images/tallinn/IMG_1516.JPG",
            "images/tallinn/IMG_1525.JPG",
            "images/tallinn/IMG_1534.JPG",
            "images/tallinn/IMG_1549.JPG",
            "images/tallinn/IMG_1561.JPG",
            "images/tallinn/IMG_1577.JPG",
            "images/tallinn/IMG_1589.JPG",
            "images/tallinn/IMG_1611.JPG",
            "images/tallinn/IMG_1625.JPG",
            "images/tallinn/IMG_1631.JPG",
            "images/tallinn/IMG_1646.JPG",
            "images/tallinn/IMG_1652.JPG",
            "images/tallinn/IMG_1678.JPG"
        ]
    },
    {
        id: "riga",
        city: "Riga",
        city_de: "Riga",
        country: "Lettonie",
        country_de: "Lettland",
        transport: "bus",
        theme: "latvia",
        text: `La Lettonie ressemble davantage au communisme d’avant. Les gens y sont d’une gentillesse débordante. Le froid signifie beaucoup de choses : la solitude, la température, l’atmosphère.`,
        text_de: `Lettland ähnelt eher dem Kommunismus von früher. Die Menschen dort sind von einer überbordenden Freundlichkeit. Kälte bedeutet vieles: Einsamkeit, Temperatur, Atmosphäre.`,
        images: [
            "images/riga/IMG_1690.JPG",
            "images/riga/IMG_1704.JPG",
            "images/riga/IMG_1712.JPG",
            "images/riga/IMG_1716.JPG",
            "images/riga/IMG_1719.JPG",
            "images/riga/IMG_1723.JPG",
            "images/riga/IMG_1726.JPG",
            "images/riga/IMG_1731.JPG",
            "images/riga/IMG_1734.JPG",
            "images/riga/IMG_1736.JPG",
            "images/riga/IMG_1741.JPG",
            "images/riga/IMG_1746.JPG",
            "images/riga/IMG_1760.JPG",
            "images/riga/IMG_1763.JPG",
            "images/riga/IMG_1768.JPG",
            "images/riga/IMG_1792.JPG",
            "images/riga/IMG_1806.JPG",
            "images/riga/IMG_1838.JPG",
            "images/riga/IMG_1852.JPG",
            "images/riga/IMG_1873.JPG",
            "images/riga/IMG_1904.JPG",
            "images/riga/IMG_1913.JPG",
            "images/riga/IMG_1937.JPG",
            "images/riga/IMG_1968.JPG",
            "images/riga/IMG_1992.JPG"
        ]
    },
    {
        id: "varsovie",
        city: "Varsovie",
        city_de: "Warschau",
        country: "Pologne",
        country_de: "Polen",
        transport: "train",
        theme: "poland",
        text: `Après une longue nuit dans ce car polonais, je me sens assommé à l’arrivée. Un froid que je n’avais jamais ressenti m’a paralysé.\n\nLe soir, je retournai à la gare de Warszawa Centralna pour prendre le train Chopin, direction Praha hlavní nádraží.`,
        text_de: `Nach einer langen Nacht in diesem polnischen Bus fühle ich mich bei der Ankunft wie erschlagen. Eine Kälte, die ich noch nie zuvor gespürt hatte, lähmte mich.\n\nAm Abend kehrte ich zum Bahnhof Warszawa Centralna zurück, um den Chopin-Zug Richtung Praha hlavní nádraží zu nehmen.`,
        images: [
            "images/varsovie/000118380024.jpg",
            "images/varsovie/000118380025.jpg",
            "images/varsovie/000118380026.jpg",
            "images/varsovie/000118380027.jpg",
            "images/varsovie/IMG_2020.JPG",
            "images/varsovie/IMG_2031.JPG",
            "images/varsovie/IMG_2056.JPG",
            "images/varsovie/IMG_2058.JPG",
            "images/varsovie/IMG_2080.JPG",
            "images/varsovie/IMG_2092.JPG",
            "images/varsovie/IMG_2100.JPG",
            "images/varsovie/IMG_2108.JPG",
            "images/varsovie/IMG_2116.JPG",
            "images/varsovie/IMG_2121.JPG",
            "images/varsovie/IMG_2209.JPG",
            "images/varsovie/IMG_2225.JPG",
            "images/varsovie/IMG_2247.JPG"
        ]
    },
    {
        id: "prague",
        city: "Prague",
        city_de: "Prag",
        country: "République Tchèque",
        country_de: "Tschechien",
        transport: "avion",
        theme: "czechia",
        text: `Prague est une belle ville. J’ai surtout aimé sa ressemblance avec la Suisse : cétait comme retrouver mon chez-moi. Prague a été profondément marquée par l’influence du Kremlin.\n\nCe soir-là, je partis pour la Suisse avec un goût amer en bouche. Comment peut-on être à ce point aveugle à la misère ?`,
        text_de: `Prag ist eine wunderschöne Stadt. Mir hat vor allem die Ähnlichkeit mit der Schweiz gefallen: Es war, als würde ich mein Zuhause wiederfinden. Prag war tief geprägt vom Einfluss des Kremls.\n\nAn jenem Abend reiste ich mit einem bitteren Beigeschmack im Mund in die Schweiz ab. Wie kann man nur so blind gegenüber dem Elend sein?`,
        images: [
            "images/prague/000118380001.jpg",
            "images/prague/000118380002.jpg",
            "images/prague/000118380003.jpg",
            "images/prague/000118380004.jpg",
            "images/prague/000118380006.jpg",
            "images/prague/000118380007.jpg",
            "images/prague/000118380009.jpg",
            "images/prague/000118380010.jpg",
            "images/prague/000118380011.jpg",
            "images/prague/000118380013.jpg",
            "images/prague/000118380014.jpg",
            "images/prague/000118380017.jpg",
            "images/prague/000118380019.jpg",
            "images/prague/000118380022.jpg",
            "images/prague/IMG_2253.JPG",
            "images/prague/IMG_2256.JPG",
            "images/prague/IMG_2267.JPG",
            "images/prague/IMG_2271.JPG",
            "images/prague/IMG_2335.JPG",
            "images/prague/IMG_2343.JPG",
            "images/prague/IMG_2362.JPG",
            "images/prague/IMG_2367.JPG",
            "images/prague/IMG_2374.JPG",
            "images/prague/IMG_2395.JPG",
            "images/prague/IMG_2399.JPG"
        ]
    },
    {
        id: "about",
        city: "À propos de l'auteur",
        city_de: "Über den Autor",
        country: "Mazin",
        country_de: "Mazin",
        transport: "none",
        theme: "author",
        text: "Je m'appelle Mazin, et ce voyage est le reflet de ma quête d'identité entre l'Orient et l'Occident.\n\nPassionné d'informatique et d'histoire, j'ai voulu documenter ces moments de vie à travers une interface qui rappelle mes premiers pas sur un ordinateur.",
        text_de: "Mein Name ist Mazin, und diese Reise spiegelt meine Suche nach Identität zwischen Orient und Okzident wider.\n\nAus Leidenschaft für Informatik und Geschichte wollte ich diese Lebensmomente durch eine Benutzeroberfläche dokumentieren, die an meine ersten Schritte am Computer erinnert.",
        images: []
    },
    {
        id: "project",
        city: "Le Projet",
        city_de: "Das Projekt",
        country: "Documentation",
        country_de: "Dokumentation",
        transport: "fin",
        theme: "project",
        text: "Ce site est une SPA narrative utilisant des technologies web modernes pour simuler un système rétro.\n\nChaque pays dispose d'un univers visuel propre, codé en CSS pour refléter l'âme du voyage.",
        text_de: "Diese Website ist eine narrative SPA, die moderne Webtechnologien nutzt, um ein Retrosystem zu simulieren.\n\nJedes Land verfügt über ein eigenes visuelles Universum, das in CSS kodiert ist, um die Seele der Reise widerzuspiegeln.",
        images: []
    }
];

const poems = [
    {
        title: "Demain, dès l'aube...",
        title_de: "Morgen, bei Tagesanbruch...",
        author: "Victor Hugo",
        text: "Demain, dès l'aube, à l'heure où blanchit la campagne,\nJe partirai. Vois-tu, je sais que tu m'attends.\nJ'irai par la forêt, j'irai par la montagne.\nJe ne puis demeurer loin de toi plus longtemps.",
        text_de: "Morgen, bei Tagesanbruch, wenn die Felder hell werden,\nwerde ich aufbrechen. Siehst du, ich weiß, dass du auf mich wartest.\nIch werde durch den Wald gehen, ich werde über die Berge gehen.\nIch kann nicht länger fern von dir bleiben."
    },
    {
        title: "Le Pont Mirabeau",
        title_de: "Die Mirabeau-Brücke",
        author: "Guillaume Apollinaire",
        text: "Sous le pont Mirabeau coule la Seine\nEt nos amours\nFaut-il qu'il m'en souvienne\nLa joie venait toujours après la peine",
        text_de: "Unter der Mirabeau-Brücke fließt die Seine\nUnd unsere Lieben\nMuss ich mich daran erinnern\nDie Freude kam immer nach dem Leid"
    },
    {
        title: "Sensation",
        title_de: "Sensation",
        author: "Arthur Rimbaud",
        text: "Par les soirs bleus d'été, j'irai dans les sentiers,\nPicoté par les blés, fouler l'herbe menue :\nRêveur, j'en sentirai la fraîcheur à mes pieds.\nJe laisserai le vent baigner ma tête nue.",
        text_de: "An blauen Sommerabenden werde ich über die Pfade gehen,\nvon Ähren gestochen, das feine Gras zertreten:\nTräumend werde ich seine Frische an meinen Füßen spüren.\nIch werde den Wind meinen nackten Kopf baden lassen."
    },
    {
        title: "Le Dormeur du val",
        title_de: "Der Schläfer im Tal",
        author: "Arthur Rimbaud",
        text: "C'est un trou de verdure où chante une rivière,\nAccrochant follement aux herbes des haillons\nD'argent ; où le soleil, de la montagne fière,\nLuit : c'est un petit val qui mousse de rayons.",
        text_de: "Es ist eine grüne Mulde, wo ein Fluss singt,\nder wahnsinnig an den Gräsern silberne Fetzen\naufhängt; wo die Sonne vom stolzen Berg\nleuchtet: es ist ein kleines Tal, das von Strahlen schäumt."
    },
    {
        title: "Correspondances",
        title_de: "Entsprechungen",
        author: "Charles Baudelaire",
        text: "La Nature est un temple où de vivants piliers\nLaissent parfois sortir de confuses paroles ;\nL'homme y passe à travers des forêts de symboles\nQui l'observent avec des regards familiers.",
        text_de: "Die Natur ist ein Tempel, in dem lebende Säulen\nmanchmal wirre Worte entweichen lassen;\nder Mensch geht dort durch Wälder von Symbolen,\ndie ihn mit vertrauten Blicken beobachten."
    }
];

const uiStrings = {
    fr: {
        login_title: "Système d'Accès Souvenir",
        login_pass: "Veuillez entrer le mot de passe pour charger les archives.",
        login_placeholder: "Mot de passe...",
        booting: "Chargement des médias...",
        next: "Continuer le voyage",
        finish: "Terminer l'aventure",
        payment_title: "Paiement Sécurisé",
        payment_choice: "Veuillez choisir votre méthode de paiement :",
        payment_card: "Carte de Crédit Imaginaire",
        payment_gold: "Or de Leprechaun",
        payment_cacao: "Fèves de Cacao",
        payment_note: "Note: Aucun remboursement possible après le départ du ferry.",
        payment_success: "Paiement accepté ! Vous pouvez maintenant continuer votre voyage vers la Finlande.",
        access_denied: "Accès Refusé",
        access_denied_msg: "Vous devez régler vos achats IKEA avant de quitter la Suède !",
        cart_title: "Smarte Shopping Cart (SEK)",
        cart_empty: "Votre panier est vide.",
        pay: "PAYER",
        archives: "Mes Archives",
        video_final: "Vidéo Final",
        poems: "Poèmes",
        language: "Langue",
        add_to_cart: "Ajouter au panier"
    },
    de: {
        login_title: "Erinnerungszugangssystem",
        login_pass: "Bitte geben Sie das Passwort ein, um die Archive zu laden.",
        login_placeholder: "Passwort...",
        booting: "Medien werden geladen...",
        next: "Reise fortsetzen",
        finish: "Abenteuer beenden",
        payment_title: "Sichere Zahlung",
        payment_choice: "Bitte wählen Sie Ihre Zahlungsmethode:",
        payment_card: "Imaginäre Kreditkarte",
        payment_gold: "Leprechaun-Gold",
        payment_cacao: "Kakaobohnen",
        payment_note: "Hinweis: Keine Rückerstattung nach Abfahrt der Fähre möglich.",
        payment_success: "Zahlung akzeptiert! Sie können nun Ihre Reise nach Finnland fortsetzen.",
        access_denied: "Zugriff verweigert",
        access_denied_msg: "Sie müssen Ihre IKEA-Einkäufe bezahlen, bevor Sie Schweden verlassen!",
        cart_title: "Smarter Warenkorb (SEK)",
        cart_empty: "Ihr Warenkorb ist leer.",
        pay: "BEZAHLEN",
        archives: "Meine Archive",
        video_final: "Finales Video",
        poems: "Gedichte",
        language: "Sprache",
        add_to_cart: "In den Warenkorb"
    }
};
